import calculator.Calculator
import numbers.ArrayOfNumbers
import strings.StringRelatedExercises

fun main(args: Array<String>) {
    println("----------------------------------------------------------------------------------------------")
    println("Initializing calculator class with values 10 and 2")
    val calculator = Calculator(num1=10, num2=2)
    println("----------------------------------------------------------------------------------------------")
    println("The addition value is ${calculator.add()}")
    println("----------------------------------------------------------------------------------------------")
    println("The subtraction value is ${calculator.subtract()}")
    println("----------------------------------------------------------------------------------------------")
    println("The division value is ${calculator.divide()}")
    println("----------------------------------------------------------------------------------------------" )
    println("The multiplication value is ${calculator.multiply()}")
    println("----------------------------------------------------------------------------------------------" )
    println("----------------------------------------------------------------------------------------------")
    println("Initializing ArrayOfNumbers class with values 2, 1, 9, 16, and 10")
    val arrayOfNumbers = ArrayOfNumbers(numbers = intArrayOf(2, 1, 9, 16, 10))
    println("----------------------------------------------------------------------------------------------")
    println("The highest value is ${arrayOfNumbers.getHighestNumber()}")
    println("----------------------------------------------------------------------------------------------")

    println("----------------------------------------------------------------------------------------------")
    println("Initializing strings class with values 'hellLo world' and 'l'")
    val testStringEx1 = StringRelatedExercises(stringVar="hellLo World", charVar='l')
    println("----------------------------------------------------------------------------------------------")
    println("The string value is ${testStringEx1.getStringVar()}")
    println("----------------------------------------------------------------------------------------------")
    println("The string value reversed is ${testStringEx1.reverseString()}")
    println("----------------------------------------------------------------------------------------------")
    println("The string value is a palindrome: ${testStringEx1.isAPalindrome()}")
    println("----------------------------------------------------------------------------------------------")
    println("The char value is ${testStringEx1.getCharVar()}")
    println("----------------------------------------------------------------------------------------------")
    println("The char value occurs ${testStringEx1.getNumberOfOccurrences()} times in the string: ${testStringEx1.getStringVar()}")
    println("----------------------------------------------------------------------------------------------")

    println("----------------------------------------------------------------------------------------------")
    println("Initializing strings class with values 'A man, a plan, a canal, Panama'")
    val testStringEx2 = StringRelatedExercises(stringVar="A man, a plan, a canal, Panama")
    println("----------------------------------------------------------------------------------------------")
    println("The string value is ${testStringEx2.getStringVar()}")
    println("----------------------------------------------------------------------------------------------")
    println("The string value capitalized is ${testStringEx2.capitalizeAllWordsInString()}")
    println("----------------------------------------------------------------------------------------------")
    println("The string value reversed is ${testStringEx2.reverseString()}")
    println("----------------------------------------------------------------------------------------------")
    println("The string value is a palindrome: ${testStringEx2.isAPalindrome()}")
    println("----------------------------------------------------------------------------------------------")
    println("The char value is ${testStringEx2.getCharVar()}")
    println("----------------------------------------------------------------------------------------------")


}