import linkedList.LinkedList

fun main() {
    println("-----------------------------------------------------------------------------------------------------------")
    println("Implementing linked list")
    val linkedList = LinkedList(head = null, tail = null)
    println("-----------------------------------------------------------------------------------------------------------")
    println("Adding 3 items")
    linkedList.add(1)
    println("Linked list tail: ${linkedList.tail}")
    linkedList.add(2)
    println("Linked list tail: ${linkedList.tail}")
    linkedList.add(3)
    println("Linked list tail: ${linkedList.tail}")
    println("-----------------------------------------------------------------------------------------------------------")
    println("These are the items in the linked list")
    println("-----------------------------------------------------------------------------------------------------------")
    linkedList.printAll()
    println("-----------------------------------------------------------------------------------------------------------")
    println("This is the length of the linked list: ${linkedList.length()}")
    println("-----------------------------------------------------------------------------------------------------------")
    println("It contains 2: ${linkedList.contains(2)}")
    println("-----------------------------------------------------------------------------------------------------------")
    println("It contains 4: ${linkedList.contains(4)}")
    println("-----------------------------------------------------------------------------------------------------------")
    println("It contains 1: ${linkedList.contains(1)}")
    println("-----------------------------------------------------------------------------------------------------------")
    println("It contains 3: ${linkedList.contains(3)}")
    println("-----------------------------------------------------------------------------------------------------------")
    println("This is the node with data of 1: ${linkedList.get(1).toString()}")
    println("-----------------------------------------------------------------------------------------------------------")
    println("This is the node with data of 0: ${linkedList.get(0).toString()}")
    println("-----------------------------------------------------------------------------------------------------------")
    println("Attempting to insert data")
    linkedList.insertAt(3, 4)
    println("-----------------------------------------------------------------------------------------------------------")
    println("These are the items in the linked list")
    linkedList.printAll()
    println("-----------------------------------------------------------------------------------------------------------")
    println("This is the node at index 2:")
    val index2 = linkedList.getAtIndex(2)
    if (index2 != null) {
        println(index2.data)
    } else {
        println(null)
    }
    println("-----------------------------------------------------------------------------------------------------------")
    println("This is the node at index 3:")
    val index3 = linkedList.getAtIndex(3)
    if (index3 != null) {
        println(index3.data)
    } else {
        println(null)
    }
    println("-----------------------------------------------------------------------------------------------------------")
    println("This is the node at index 0:")
    val index0 = linkedList.getAtIndex(0)
    if (index0 != null) {
        println(index0.data)
    } else {
        println(null)
    }
    println("-----------------------------------------------------------------------------------------------------------")
    println("This is the node at index 5:")
    val index5 = linkedList.getAtIndex(5)
    if (index5 != null) {
        println(index5.data)
    } else {
        println(null)
    }
    println("-----------------------------------------------------------------------------------------------------------")
    println("Attempting to remove data")
    linkedList.remove(2)
    println("-----------------------------------------------------------------------------------------------------------")
    println("These are the items in the linked list")
    linkedList.printAll()
    println("-----------------------------------------------------------------------------------------------------------")
    println("Linked list length: ${linkedList.length()}")
    println("Linked list tail: ${linkedList.tail}")
    println("-----------------------------------------------------------------------------------------------------------")
    println("Attempting to remove data")
    linkedList.remove(0)
    println("-----------------------------------------------------------------------------------------------------------")
    println("These are the items in the linked list")
    linkedList.printAll()
    println("-----------------------------------------------------------------------------------------------------------")
    println("Linked list length: ${linkedList.length()}")
    println("Linked list tail: ${linkedList.tail}")
    println("-----------------------------------------------------------------------------------------------------------")

}