import doublyLinkedList.DoublyLinkedList
import linkedList.LinkedList

fun main() {
    /*
    println("-----------------------------------------------------------------------------------------------------------")
    println("Implementing linked list")
    val linkedList = LinkedList(head = null, tail = null)
    println("-----------------------------------------------------------------------------------------------------------")
    println("Adding 3 items")
    linkedList.add(1)
    println("Linked list tail: ${linkedList.tail}")
    linkedList.add(2)
    println("Linked list tail: ${linkedList.tail}")
    linkedList.add(3)
    println("Linked list tail: ${linkedList.tail}")
    println("-----------------------------------------------------------------------------------------------------------")
    println("These are the items in the linked list")
    println("-----------------------------------------------------------------------------------------------------------")
    linkedList.printAll()
    println("-----------------------------------------------------------------------------------------------------------")
    println("This is the length of the linked list: ${linkedList.length()}")
    println("-----------------------------------------------------------------------------------------------------------")
    println("It contains 2: ${linkedList.contains(2)}")
    println("-----------------------------------------------------------------------------------------------------------")
    println("It contains 4: ${linkedList.contains(4)}")
    println("-----------------------------------------------------------------------------------------------------------")
    println("It contains 1: ${linkedList.contains(1)}")
    println("-----------------------------------------------------------------------------------------------------------")
    println("It contains 3: ${linkedList.contains(3)}")
    println("-----------------------------------------------------------------------------------------------------------")
    println("This is the node with data of 1: ${linkedList.get(1).toString()}")
    println("-----------------------------------------------------------------------------------------------------------")
    println("This is the node with data of 0: ${linkedList.get(0).toString()}")
    println("-----------------------------------------------------------------------------------------------------------")
    println("Attempting to insert data")
    linkedList.insertAt(3, 4)
    println("-----------------------------------------------------------------------------------------------------------")
    println("These are the items in the linked list")
    linkedList.printAll()
    println("-----------------------------------------------------------------------------------------------------------")
    println("This is the node at index 2:")
    val index2 = linkedList.getAtIndex(2)
    if (index2 != null) {
        println(index2.data)
    } else {
        println(null)
    }
    println("-----------------------------------------------------------------------------------------------------------")
    println("This is the node at index 3:")
    val index3 = linkedList.getAtIndex(3)
    if (index3 != null) {
        println(index3.data)
    } else {
        println(null)
    }
    println("-----------------------------------------------------------------------------------------------------------")
    println("This is the node at index 0:")
    val index0 = linkedList.getAtIndex(0)
    if (index0 != null) {
        println(index0.data)
    } else {
        println(null)
    }
    println("-----------------------------------------------------------------------------------------------------------")
    println("This is the node at index 5:")
    val index5 = linkedList.getAtIndex(5)
    if (index5 != null) {
        println(index5.data)
    } else {
        println(null)
    }
    println("-----------------------------------------------------------------------------------------------------------")
    println("Attempting to remove data")
    linkedList.remove(2)
    println("-----------------------------------------------------------------------------------------------------------")
    println("These are the items in the linked list")
    linkedList.printAll()
    println("-----------------------------------------------------------------------------------------------------------")
    println("Linked list length: ${linkedList.length()}")
    println("Linked list tail: ${linkedList.tail}")
    println("-----------------------------------------------------------------------------------------------------------")
    println("Attempting to remove data")
    linkedList.remove(0)
    println("-----------------------------------------------------------------------------------------------------------")
    println("These are the items in the linked list")
    linkedList.printAll()
    println("-----------------------------------------------------------------------------------------------------------")
    println("Linked list length: ${linkedList.length()}")
    println("Linked list tail: ${linkedList.tail}")
    println("-----------------------------------------------------------------------------------------------------------")
    */
    println("-----------------------------------------------------------------------------------------------------------")
    println("Implementing doubly linked list")
    val doublyLinkedList = DoublyLinkedList(head = null, tail = null)
    println("-----------------------------------------------------------------------------------------------------------")
    println("Appending 3 items")
    doublyLinkedList.append(100)
    println("Linked list tail: ${doublyLinkedList.tail?.data}")
    doublyLinkedList.append(200)
    println("Linked list tail: ${doublyLinkedList.tail?.data}")
    doublyLinkedList.append(300)
    println("Linked list tail: ${doublyLinkedList.tail?.data}")
    println("-----------------------------------------------------------------------------------------------------------")
    println("Prepending 1 item1")
    doublyLinkedList.prepend(50)
    println("Linked list head: ${doublyLinkedList.head?.data}")
    println("-----------------------------------------------------------------------------------------------------------")

    println("These are the items in the linked list")
    println("-----------------------------------------------------------------------------------------------------------")
    doublyLinkedList.printAll()
    println("-----------------------------------------------------------------------------------------------------------")
    println("Inserting new item at index 2")
    doublyLinkedList.insertAt(2, 150)
    println("-----------------------------------------------------------------------------------------------------------")
    doublyLinkedList.printAll()
    println("-----------------------------------------------------------------------------------------------------------")
    println("Inserting new item at index 5")
    doublyLinkedList.insertAt(5, 400)
    println("-----------------------------------------------------------------------------------------------------------")
    doublyLinkedList.printAll()
    println("-----------------------------------------------------------------------------------------------------------")
    println("Linked list tail: ${doublyLinkedList.tail?.data}")
    println("-----------------------------------------------------------------------------------------------------------")
    println("Inserting new item at index 0")
    doublyLinkedList.insertAt(0, 25)
    println("-----------------------------------------------------------------------------------------------------------")
    doublyLinkedList.printAll()
    println("-----------------------------------------------------------------------------------------------------------")
    println("Linked list head: ${doublyLinkedList.head?.data}")
    println("-----------------------------------------------------------------------------------------------------------")
    println("Removing item at index 1")
    doublyLinkedList.removeFrom(1)
    println("-----------------------------------------------------------------------------------------------------------")
    doublyLinkedList.printAll()
    println("-----------------------------------------------------------------------------------------------------------")
    println("Removing item at index 0")
    doublyLinkedList.removeFrom(0)
    println("-----------------------------------------------------------------------------------------------------------")
    doublyLinkedList.printAll()
    println("Linked list head: ${doublyLinkedList.head?.data}")
    println("-----------------------------------------------------------------------------------------------------------")
    println("Removing item at index 4 -- last")
    doublyLinkedList.removeFrom(4)
    println("-----------------------------------------------------------------------------------------------------------")
    doublyLinkedList.printAll()
    println("Linked list tail: ${doublyLinkedList.tail?.data}")
    println("-----------------------------------------------------------------------------------------------------------")
}