from fizzbuzz.fizzbuzz import Fizzbuzz
from array_intersection.array_intersection import ArrayIntersection
from display_likes.display_likes import DisplayLikes
from all_chars_unique.all_chars_unique import AllCharsAreUnique
from find_missing_number.find_missing_number import FindMissingNumber

if __name__ == '__main__':
	print("-----------------------------------------------------------------------------------------------")
	print("First initializing Fizzbuzz class to return values up to 15")
	fizzbuzz_obj = Fizzbuzz(15)
	fb_result = fizzbuzz_obj.get_fizzbuzz()
	print("-----------------------------------------------------------------------------------------------")
	print("This is the fizz buzz result: ")
	print(fb_result)
	print("-----------------------------------------------------------------------------------------------")
	print("Initializing object to test for common values in two lists")
	print("-----------------------------------------------------------------------------------------------")
	array_intersection_object = ArrayIntersection([1, 2, 3, 4, 5], [3, 4, 5, 6, 7])
	print("-----------------------------------------------------------------------------------------------")
	print("This is the result of the array intersection:")
	ai_result = array_intersection_object.get_list_of_values_in_both_lists()
	print(ai_result)
	print("-----------------------------------------------------------------------------------------------")
	print("-----------------------------------------------------------------------------------------------")
	print("Initializing object to find missing number in list of consecutive ascending integers (1 through 7)")
	print("-----------------------------------------------------------------------------------------------")
	find_missing_number_obj1 = FindMissingNumber([1, 2, 3, 4, 5, 7])
	print("-----------------------------------------------------------------------------------------------")
	print("This is the missing number result:")
	print(find_missing_number_obj1.get_missing_number())
	print("-----------------------------------------------------------------------------------------------")
	print("-----------------------------------------------------------------------------------------------")
	print("Initializing object to test for likes message")
	print("-----------------------------------------------------------------------------------------------")
	display_likes_object1 = DisplayLikes(["Bob"])
	print("-----------------------------------------------------------------------------------------------")
	print("This is the likes message: " + display_likes_object1.get_message())
	print("-----------------------------------------------------------------------------------------------")
	print("Initializing object to test for likes message")
	print("-----------------------------------------------------------------------------------------------")
	display_likes_object2 = DisplayLikes(["Bob", "Dana"])
	print("-----------------------------------------------------------------------------------------------")
	print("This is the likes message: " + display_likes_object2.get_message())
	print("-----------------------------------------------------------------------------------------------")
	print("Initializing object to test for likes message")
	print("-----------------------------------------------------------------------------------------------")
	display_likes_object3 = DisplayLikes(["Bob", "Alice", "Dana"])
	print("-----------------------------------------------------------------------------------------------")
	print("This is the likes message: " + display_likes_object3.get_message())
	print("-----------------------------------------------------------------------------------------------")
	print("Initializing object to test for likes message")
	print("-----------------------------------------------------------------------------------------------")
	display_likes_object4 = DisplayLikes(["Bob", "Alice", "Dana", "Louisa"])
	print("-----------------------------------------------------------------------------------------------")
	print("This is the likes message: " + display_likes_object4.get_message())
	print("-----------------------------------------------------------------------------------------------")
	print("Initializing object to test for likes message")
	print("-----------------------------------------------------------------------------------------------")
	display_likes_object5 = DisplayLikes([])
	print("-----------------------------------------------------------------------------------------------")
	print("This is the likes message: " + display_likes_object5.get_message())
	print("-----------------------------------------------------------------------------------------------")
	print("Initializing object to test for likes message")
	print("-----------------------------------------------------------------------------------------------")
	all_chars_are_unique1 = AllCharsAreUnique("bigbang")
	print("-----------------------------------------------------------------------------------------------")
	print("All of the characters in 'bigbang' are unique : " + str(all_chars_are_unique1.get_verdict()))
	print("-----------------------------------------------------------------------------------------------")
	all_chars_are_unique2 = AllCharsAreUnique("sunray")
	print("-----------------------------------------------------------------------------------------------")
	print("All of the characters in 'sunray' are unique : " + str(all_chars_are_unique2.get_verdict()))
	print("-----------------------------------------------------------------------------------------------")
	all_chars_are_unique3 = AllCharsAreUnique("")
	print("-----------------------------------------------------------------------------------------------")
	print("All of the characters in empty string are unique : " + str(all_chars_are_unique3.get_verdict()))
	print("-----------------------------------------------------------------------------------------------")

